import { useEffect, useState } from "react";
import type { TFunction } from "i18next";
import { useTranslation } from "react-i18next";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "@/features/auth/auth-state";
import { TicketPriorityText, TicketStatusBadge } from "./ticket-badges";
import { getTicketError, getTicketErrorStatus } from "./ticket-error";
import { formatTicketDate, ticketReference } from "./ticket-format";
import { useAgents, useCategories, useTicket, useUpdateTicket } from "./ticket-hooks";
import type { TicketPriority, TicketStatus } from "./ticket.types";
import { TicketPage, TicketSkeleton, TicketState } from "./ticket-ui";

const normalTransitions: Record<TicketStatus, TicketStatus[]> = { NEW: ["OPEN"], OPEN: ["IN_PROGRESS"], IN_PROGRESS: ["WAITING_CUSTOMER", "RESOLVED"], WAITING_CUSTOMER: ["IN_PROGRESS", "RESOLVED"], RESOLVED: ["CLOSED"], CLOSED: [], ESCALATED: [] };
export function TicketDetailPage() {
  const { t, i18n } = useTranslation(); const { id = "" } = useParams(); const { user } = useAuth(); const ticket = useTicket(id); const update = useUpdateTicket(id); const categories = useCategories(); const agents = useAgents();
  const [status, setStatus] = useState<TicketStatus | "">(""); const [priority, setPriority] = useState<TicketPriority | "">(""); const [categoryId, setCategoryId] = useState(""); const [assignedAgentId, setAssignedAgentId] = useState(""); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (ticket.data) { setStatus(ticket.data.status); setPriority(ticket.data.priority); setCategoryId(ticket.data.category?.id ?? ""); setAssignedAgentId(ticket.data.assignedAgent?.id ?? ""); } }, [ticket.data]);
  if (ticket.isLoading) return <TicketPage><TicketSkeleton /></TicketPage>;
  if (ticket.isError || !ticket.data) { const statusCode = getTicketErrorStatus(ticket.error); return <TicketPage><TicketState>{statusCode === 404 ? t("tickets.notFound") : statusCode === 403 ? t("tickets.unauthorized") : t("tickets.loadDetailError")}</TicketState></TicketPage>; }
  const record = ticket.data; const canAssign = user?.role === "ADMIN" || user?.role === "MANAGER"; const assignedToMe = record.assignedAgent?.id === user?.id; const canWorkflow = canAssign || assignedToMe;
  const availableStatuses = [...normalTransitions[record.status], ...(canAssign && ["NEW", "OPEN", "IN_PROGRESS", "WAITING_CUSTOMER"].includes(record.status) ? ["ESCALATED" as TicketStatus] : []), ...(canAssign && record.status === "ESCALATED" ? ["IN_PROGRESS" as TicketStatus] : [])];
  const saveOperations = async () => { setError(null); const changes: { status?: TicketStatus; priority?: TicketPriority; categoryId?: string | null; assignedAgentId?: string | null } = {};
    if (status && status !== record.status) changes.status = status; if (priority && priority !== record.priority) changes.priority = priority; if (categoryId !== (record.category?.id ?? "")) changes.categoryId = categoryId || null; if (canAssign && assignedAgentId !== (record.assignedAgent?.id ?? "")) changes.assignedAgentId = assignedAgentId || null;
    if (!Object.keys(changes).length) return; try { await update.mutateAsync(changes); } catch (caught) { setError(getTicketError(caught, t("tickets.updateError"), t)); }
  };
  return <TicketPage>
    <header className="border-b pb-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><Link className="text-sm font-medium text-primary" to="/tickets">{t("tickets.backToList")}</Link><p className="mt-4 text-xs text-muted-foreground" dir="ltr">{ticketReference(record.id)}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">{record.subject}</h1><div className="mt-3 flex flex-wrap items-center gap-3"><TicketStatusBadge status={record.status} /><TicketPriorityText priority={record.priority} /><span className="text-xs text-muted-foreground">{t(`tickets.channel.${record.channel}`)}</span></div></div><Link className="button-secondary" to={`/tickets/${record.id}/edit`}>{t("common.edit")}</Link></div></header>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
      <div className="space-y-6"><section className="rounded-md border bg-white p-5"><h2 className="text-base font-semibold">{t("tickets.descriptionLabel")}</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{record.description}</p></section>
        <section className="rounded-md border bg-white"><div className="border-b px-5 py-4"><h2 className="text-base font-semibold">{t("tickets.history")}</h2></div>{record.history.length ? <ol className="divide-y">{record.history.map((event) => <li className="px-5 py-4" key={event.id}><div className="flex flex-col gap-1 sm:flex-row sm:items-baseline sm:justify-between"><p className="text-sm font-medium">{t(`tickets.historyActions.${event.action}`, { defaultValue: event.action })}</p><time className="text-xs text-muted-foreground">{formatTicketDate(event.createdAt, i18n.language)}</time></div><p className="mt-1 text-xs text-muted-foreground">{event.actor?.name ?? t("tickets.systemActor")}{event.oldValue || event.newValue ? `: ${event.oldValue ? displayValue(event.oldValue, t) : t("common.notProvided")} → ${event.newValue ? displayValue(event.newValue, t) : t("common.notProvided")}` : ""}</p></li>)}</ol> : <p className="p-5 text-sm text-muted-foreground">{t("tickets.noHistory")}</p>}</section>
        <section className="rounded-md border border-dashed bg-muted/30 p-5"><h2 className="text-base font-semibold">{t("tickets.conversationLaterTitle")}</h2><p className="mt-1 text-sm text-muted-foreground">{t("tickets.conversationLater")}</p></section>
      </div>
      <aside className="space-y-5"><section className="rounded-md border bg-white p-5"><h2 className="text-base font-semibold">{t("tickets.operations")}</h2>{error && <p className="mt-3 rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}<div className="mt-4 space-y-4">
        <Control label={t("tickets.statusLabel")}><select className="input" value={status} disabled={!canWorkflow || availableStatuses.length === 0} onChange={(event) => setStatus(event.target.value as TicketStatus)}><option value={record.status}>{t(`tickets.status.${record.status}`)}</option>{availableStatuses.filter((value) => value !== record.status).map((value) => <option value={value} key={value}>{t(`tickets.status.${value}`)}</option>)}</select></Control>
        <Control label={t("tickets.priorityLabel")}><select className="input" value={priority} disabled={!canWorkflow} onChange={(event) => setPriority(event.target.value as TicketPriority)}>{["LOW", "MEDIUM", "HIGH", "URGENT"].map((value) => <option value={value} key={value}>{t(`tickets.priority.${value}`)}</option>)}</select></Control>
        <Control label={t("tickets.category")}><select className="input" value={categoryId} onChange={(event) => setCategoryId(event.target.value)}><option value="">{t("common.notProvided")}</option>{categories.data?.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Control>
        {canAssign && <Control label={t("tickets.assignedAgent")}><select className="input" value={assignedAgentId} onChange={(event) => setAssignedAgentId(event.target.value)}><option value="">{t("tickets.unassigned")}</option>{agents.data?.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Control>}
        <button className="button-primary" disabled={update.isPending} onClick={saveOperations}>{update.isPending ? t("common.saving") : t("tickets.saveOperations")}</button></div></section>
        <section className="rounded-md border bg-white p-5"><h2 className="text-base font-semibold">{t("tickets.customer")}</h2><Link className="mt-3 block font-medium text-primary" to={`/customers/${record.customer.id}`}>{record.customer.name}</Link><p className="mt-1 text-sm text-muted-foreground"><bdi dir="ltr">{record.customer.email}</bdi></p>{record.customer.phone && <p className="text-sm text-muted-foreground"><bdi dir="ltr">{record.customer.phone}</bdi></p>}</section>
        <section className="rounded-md border bg-white p-5"><h2 className="text-base font-semibold">{t("tickets.metadata")}</h2><dl className="mt-3 space-y-3 text-sm"><Meta label={t("tickets.category")} value={record.category?.name ?? t("common.notProvided")} /><Meta label={t("tickets.assignedAgent")} value={record.assignedAgent?.name ?? t("tickets.unassigned")} /><Meta label={t("tickets.created")} value={formatTicketDate(record.createdAt, i18n.language)} /><Meta label={t("tickets.updated")} value={formatTicketDate(record.updatedAt, i18n.language)} /><Meta label={t("tickets.firstResponseDue")} value={record.firstResponseDueAt ? formatTicketDate(record.firstResponseDueAt, i18n.language) : t("common.notProvided")} /><Meta label={t("tickets.resolutionDue")} value={record.resolutionDueAt ? formatTicketDate(record.resolutionDueAt, i18n.language) : t("common.notProvided")} /></dl></section>
      </aside>
    </div>
  </TicketPage>;
}
function Control({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="text-sm font-medium">{label}</span><span className="mt-2 block">{children}</span></label>; }
function Meta({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4"><dt className="text-muted-foreground">{label}</dt><dd className="text-end">{value}</dd></div>; }
function displayValue(value: string, t: TFunction) { if (["NEW", "OPEN", "IN_PROGRESS", "WAITING_CUSTOMER", "RESOLVED", "CLOSED", "ESCALATED"].includes(value)) return t(`tickets.status.${value}`); if (["LOW", "MEDIUM", "HIGH", "URGENT"].includes(value)) return t(`tickets.priority.${value}`); return value; }
