import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { SettingsPage } from "./settings-page";
const hooks = vi.hoisted(() => ({ categories: { isLoading: false, isError: false, data: [] as unknown[], refetch: vi.fn() }, sla: { isLoading: false, isError: false, data: [] as unknown[], refetch: vi.fn() }, mutateAsync: vi.fn() }));
vi.mock("./settings-hooks", () => ({ useSettingCategories: () => hooks.categories, useSlaRules: () => hooks.sla, useCreateCategory: () => ({ isPending: false, mutateAsync: hooks.mutateAsync }), useUpdateCategory: () => ({ isPending: false, mutateAsync: hooks.mutateAsync }), usePutSlaRule: () => ({ isPending: false, mutateAsync: hooks.mutateAsync }) }));
afterEach(cleanup);
describe("SettingsPage", () => { beforeEach(() => { hooks.categories = { isLoading: false, isError: false, data: [], refetch: vi.fn() }; hooks.sla = { isLoading: false, isError: false, data: [], refetch: vi.fn() }; }); it("shows the real sections without General or Branding", () => { render(<MemoryRouter><SettingsPage /></MemoryRouter>); expect(screen.getByRole("heading", { name: "settings.title" })).toBeInTheDocument(); expect(screen.getByRole("button", { name: "settings.tabs.categories" })).toBeInTheDocument(); expect(screen.queryByText("General")).not.toBeInTheDocument(); expect(screen.queryByText("Branding")).not.toBeInTheDocument(); }); it("renders empty and no-results category states", () => { render(<MemoryRouter><SettingsPage /></MemoryRouter>); expect(screen.getByText("settings.categories.empty")).toBeInTheDocument(); fireEvent.change(screen.getByPlaceholderText("settings.categories.search"), { target: { value: "none" } }); expect(screen.getByText("settings.categories.noResults")).toBeInTheDocument(); }); it("links to the existing Quick Replies workspace", () => { render(<MemoryRouter><SettingsPage /></MemoryRouter>); fireEvent.click(screen.getByRole("button", { name: "settings.tabs.quick" })); expect(screen.getByRole("link", { name: "settings.quick.open" })).toHaveAttribute("href", "/quick-replies"); }); it("renders four SLA priority editors", () => { render(<MemoryRouter><SettingsPage /></MemoryRouter>); fireEvent.click(screen.getByRole("button", { name: "settings.tabs.sla" })); expect(screen.getAllByText("settings.sla.missing")).toHaveLength(4); }); });

describe("category status confirmation", () => { afterEach(cleanup); it("uses a portalled site dialog instead of window.confirm", () => { hooks.categories = { isLoading: false, isError: false, data: [{ id: "c1", name: "Billing", description: null, isActive: true, createdAt: "", updatedAt: "" }], refetch: vi.fn() }; const nativeConfirm = vi.spyOn(window, "confirm"); render(<MemoryRouter><SettingsPage /></MemoryRouter>); fireEvent.click(screen.getAllByRole("button", { name: "settings.deactivate" })[0]); expect(screen.getByRole("alertdialog")).toBeInTheDocument(); expect(screen.getByText("settings.categories.deactivateTitle")).toBeInTheDocument(); expect(nativeConfirm).not.toHaveBeenCalled(); nativeConfirm.mockRestore(); }); });

describe("category editor dialog", () => { afterEach(cleanup); it("opens empty for add and prefilled for edit", () => { hooks.categories = { isLoading: false, isError: false, data: [{ id: "c1", name: "Billing", description: "Invoices", isActive: true, createdAt: "", updatedAt: "" }], refetch: vi.fn() }; render(<MemoryRouter><SettingsPage /></MemoryRouter>); fireEvent.click(screen.getByRole("button", { name: "settings.categories.create" })); expect(screen.getByRole("dialog")).toBeInTheDocument(); expect(screen.getByRole("textbox", { name: "settings.categories.name" })).toHaveValue(""); fireEvent.click(screen.getByRole("button", { name: "common.cancel" })); fireEvent.click(screen.getAllByRole("button", { name: "common.edit" })[0]); expect(screen.getByRole("dialog")).toBeInTheDocument(); expect(screen.getByRole("textbox", { name: "settings.categories.name" })).toHaveValue("Billing"); expect(screen.getByRole("textbox", { name: "settings.categories.fieldDescription" })).toHaveValue("Invoices"); }); });
