import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useAuth } from "../auth/auth-state";
import { formatTicketDate, ticketReference } from "../tickets/ticket-format";
import { TicketPriorityText, TicketStatusBadge } from "../tickets/ticket-badges";
import { useDashboardOverview } from "./dashboard-hooks";
import type { DashboardOverview, DashboardTicket } from "./dashboard.types";

export function DashboardPage() {
  const { t, i18n } = useTranslation(); const { user } = useAuth(); const query = useDashboardOverview();
  if (query.isLoading) return <main className="page-container" aria-label={t("common.loading")}><DashboardSkeleton /></main>;
  if (query.isError || !query.data) return <main className="page-container"><State text={t("dashboard.loadError")}><button className="button-secondary" onClick={() => query.refetch()}>{t("common.retry")}</button></State></main>;
  const data = query.data; const isAgent = user?.role === "AGENT";
  const metrics = isAgent
    ? [["assignedToMe", data.metrics.assignedToMe], ["slaBreached", data.metrics.slaBreached], ["slaAtRisk", data.metrics.slaAtRisk], ["waitingCustomer", data.metrics.waitingCustomer], ["resolvedToday", data.metrics.resolvedToday]] as const
    : [["openTickets", data.metrics.openTickets], ["unassignedTickets", data.metrics.unassignedTickets], ["slaBreached", data.metrics.slaBreached], ["slaAtRisk", data.metrics.slaAtRisk], ["resolvedToday", data.metrics.resolvedToday]] as const;
  return <main className="page-container space-y-6">
    <header className="border-b pb-5"><h1 className="text-2xl font-semibold tracking-tight">{t("dashboard.title")}</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">{t("dashboard.description")}</p></header>
    <section className="grid grid-cols-2 gap-px overflow-hidden rounded-md border bg-border lg:grid-cols-5" aria-label={t("dashboard.metricsLabel")}>
      {metrics.map(([key, value]) => <div className="min-w-0 bg-white px-4 py-3" key={key}><p className="truncate text-xs font-medium text-muted-foreground">{t(`dashboard.metrics.${key}`)}</p><p className="mt-1 text-2xl font-semibold tabular-nums" dir="ltr">{new Intl.NumberFormat(i18n.language === "ar" ? "ar-EG" : "en-US").format(value)}</p></div>)}
    </section>
    <section className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(16rem,1fr)]">
      <Distribution data={data} />
      <div className="rounded-md border bg-white p-5"><h2 className="text-base font-semibold">{t("dashboard.summaryTitle")}</h2><dl className="mt-4 space-y-3"><Summary label={t("dashboard.metrics.waitingCustomer")} value={data.metrics.waitingCustomer} /><Summary label={t(`dashboard.metrics.${isAgent ? "assignedToMe" : "unassignedTickets"}`)} value={isAgent ? data.metrics.assignedToMe : data.metrics.unassignedTickets} /><Summary label={t("dashboard.generatedAt")} value={formatTicketDate(data.generatedAt, i18n.language)} technical /></dl></div>
    </section>
    <TicketSection title={t("dashboard.needsAttention")} empty={t("dashboard.emptyAttention")} tickets={data.needsAttention} detailed />
    <TicketSection title={t("dashboard.recentTickets")} empty={t("dashboard.emptyRecent")} tickets={data.recentTickets} />
    <div><Link className="text-sm font-medium text-primary hover:underline" to="/tickets">{t("dashboard.viewAll")}</Link></div>
  </main>;
}

function Distribution({ data }: { data: DashboardOverview }) { const { t } = useTranslation(); const chart = data.statusDistribution.map((item) => ({ ...item, label: t(`tickets.status.${item.status}`) })); return <section className="rounded-md border bg-white p-5" aria-labelledby="dashboard-chart-title" aria-describedby="dashboard-chart-description"><h2 id="dashboard-chart-title" className="text-base font-semibold">{t("dashboard.chartTitle")}</h2><p id="dashboard-chart-description" className="mt-1 text-xs text-muted-foreground">{t("dashboard.chartDescription")}</p>{chart.length ? <><div className="mt-4 h-56" data-testid="status-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} layout="vertical" margin={{ left: 8, right: 8 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} /><XAxis type="number" allowDecimals={false} /><YAxis dataKey="label" type="category" width={110} tick={{ fontSize: 11 }} /><Tooltip formatter={(value) => [value, t("dashboard.ticketsCount")]} /><Bar dataKey="count" fill="var(--primary)" radius={[0, 3, 3, 0]} isAnimationActive={false} /></BarChart></ResponsiveContainer></div><ul className="sr-only">{chart.map((item) => <li key={item.status}>{item.label}: {item.count}</li>)}</ul></> : <p className="mt-6 text-sm text-muted-foreground">{t("dashboard.emptyDistribution")}</p>}</section>; }
function TicketSection({ title, empty, tickets, detailed = false }: { title: string; empty: string; tickets: DashboardTicket[]; detailed?: boolean }) { const { t, i18n } = useTranslation(); return <section><h2 className="text-base font-semibold">{title}</h2>{tickets.length ? <><div className="mt-3 hidden overflow-hidden rounded-md border bg-white md:block"><table className="w-full table-fixed text-sm"><thead className="bg-muted text-xs text-muted-foreground"><tr><th className="w-28 px-3 py-2 text-start">{t("tickets.columns.id")}</th><th className="px-3 py-2 text-start">{t("tickets.subject")}</th>{detailed && <th className="w-36 px-3 py-2 text-start">{t("tickets.customer")}</th>}<th className="w-28 px-3 py-2 text-start">{t("tickets.priorityLabel")}</th><th className="w-36 px-3 py-2 text-start">{t("tickets.statusLabel")}</th>{detailed && <th className="w-32 px-3 py-2 text-start">{t("dashboard.sla")}</th>}<th className="w-36 px-3 py-2 text-start">{t("tickets.assignedAgent")}</th><th className="w-40 px-3 py-2 text-start">{t("tickets.updated")}</th></tr></thead><tbody className="divide-y">{tickets.map((ticket) => <tr key={ticket.id}><td className="px-3 py-2"><Link className="font-medium text-primary hover:underline" to={`/tickets/${ticket.id}`} dir="ltr">{ticketReference(ticket.id)}</Link></td><td className="truncate px-3 py-2" title={ticket.subject}>{ticket.subject}</td>{detailed && <td className="truncate px-3 py-2">{ticket.customer.name}</td>}<td className="px-3 py-2"><TicketPriorityText priority={ticket.priority} /></td><td className="px-3 py-2"><TicketStatusBadge status={ticket.status} /></td>{detailed && <td className="px-3 py-2"><Sla state={ticket.slaState} /></td>}<td className="truncate px-3 py-2">{ticket.assignedAgent?.name ?? t("tickets.unassigned")}</td><td className="px-3 py-2 text-xs text-muted-foreground" dir="ltr">{formatTicketDate(ticket.updatedAt, i18n.language)}</td></tr>)}</tbody></table></div><div className="mt-3 grid gap-3 md:hidden">{tickets.map((ticket) => <Link className="rounded-md border bg-white p-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/30" to={`/tickets/${ticket.id}`} key={ticket.id}><div className="flex items-center justify-between gap-3"><span className="font-medium text-primary" dir="ltr">{ticketReference(ticket.id)}</span><TicketPriorityText priority={ticket.priority} /></div><p className="mt-2 font-medium">{ticket.subject}</p><div className="mt-3 flex flex-wrap items-center gap-2"><TicketStatusBadge status={ticket.status} />{detailed && <Sla state={ticket.slaState} />}</div><p className="mt-3 text-xs text-muted-foreground">{ticket.assignedAgent?.name ?? t("tickets.unassigned")} · <span dir="ltr">{formatTicketDate(ticket.updatedAt, i18n.language)}</span></p></Link>)}</div></> : <p className="mt-3 rounded-md border bg-white px-4 py-8 text-center text-sm text-muted-foreground">{empty}</p>}</section>; }
function Sla({ state }: { state: DashboardTicket["slaState"] }) { const { t } = useTranslation(); const color = state === "BREACHED" ? "text-red-700" : state === "AT_RISK" ? "text-amber-700" : "text-muted-foreground"; return <span className={`text-xs font-semibold ${color}`}>{t(`dashboard.slaStates.${state}`)}</span>; }
function Summary({ label, value, technical }: { label: string; value: string | number; technical?: boolean }) { return <div className="flex items-start justify-between gap-4 border-b pb-3 last:border-0 last:pb-0"><dt className="text-sm text-muted-foreground">{label}</dt><dd className="text-end text-sm font-semibold tabular-nums" dir={technical ? "ltr" : undefined}>{value}</dd></div>; }
function State({ text, children }: { text: string; children: React.ReactNode }) { return <section className="rounded-md border bg-white px-5 py-12 text-center"><p className="text-sm text-muted-foreground">{text}</p><div className="mt-4">{children}</div></section>; }
function DashboardSkeleton() { return <div className="space-y-6"><div className="h-16 animate-pulse rounded-md bg-muted" /><div className="grid grid-cols-2 gap-2 lg:grid-cols-5">{Array.from({ length: 5 }, (_, i) => <div className="h-20 animate-pulse rounded-md bg-muted" key={i} />)}</div><div className="h-64 animate-pulse rounded-md bg-muted" /><div className="h-72 animate-pulse rounded-md bg-muted" /></div>; }
