import { Role, TicketStatus } from "@prisma/client";
import request from "supertest";
import { beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({
  customer: { findUnique: vi.fn() }, ticket: { count: vi.fn(), findMany: vi.fn(), findFirst: vi.fn(), create: vi.fn(), update: vi.fn() },
  category: { findMany: vi.fn(), findFirst: vi.fn() }, slaRule: { findFirst: vi.fn() }, ticketMessage: { create: vi.fn() }, ticketHistory: { create: vi.fn() },
  user: { findFirst: vi.fn().mockResolvedValue(null), findMany: vi.fn().mockResolvedValue([]) },
  notification: { createMany: vi.fn().mockResolvedValue({ count: 0 }) },
}));
vi.mock("../../config/prisma.js", () => ({ prisma: { ...mocks, $transaction: vi.fn(async (value: unknown) => typeof value === "function" ? (value as (tx: typeof mocks) => unknown)(mocks) : Promise.all(value as Promise<unknown>[])) } }));

import { app } from "../../app.js";
import { createAccessToken } from "../auth/auth-token.js";
import { portalStatus } from "./portal.service.js";
const auth = (id: string, role: Role) => ({ Authorization: `Bearer ${createAccessToken({ id, role })}` });
const base = { id: "ticket-a", subject: "Help", status: TicketStatus.NEW, category: null, createdAt: new Date(), updatedAt: new Date() };

describe("customer portal", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.customer.findUnique.mockResolvedValue({ id: "customer-a" }); mocks.ticket.count.mockResolvedValue(0); mocks.ticket.findMany.mockResolvedValue([]); mocks.category.findMany.mockResolvedValue([]); });

  it("rejects unauthenticated and every internal role", async () => {
    expect((await request(app).get("/api/portal/overview")).status).toBe(401);
    for (const role of [Role.ADMIN, Role.MANAGER, Role.AGENT]) expect((await request(app).get("/api/portal/overview").set(auth("staff", role))).status).toBe(403);
  });
  it("requires a linked customer profile", async () => { mocks.customer.findUnique.mockResolvedValue(null); const response = await request(app).get("/api/portal/overview").set(auth("customer", Role.CUSTOMER)); expect(response.status).toBe(403); expect(response.body.error.code).toBe("CUSTOMER_PROFILE_REQUIRED"); });
  it("scopes overview counts and recent tickets", async () => { mocks.ticket.count.mockResolvedValueOnce(4).mockResolvedValueOnce(2).mockResolvedValueOnce(1); mocks.ticket.findMany.mockResolvedValue([{ ...base, status: TicketStatus.ESCALATED }]); const response = await request(app).get("/api/portal/overview").set(auth("customer", Role.CUSTOMER)); expect(response.body.data.counts).toEqual({ open: 4, waitingForYou: 2, resolved: 1 }); expect(response.body.data.recentTickets[0].status).toBe("IN_PROGRESS"); expect(mocks.ticket.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { customerId: "customer-a" }, take: 5, orderBy: [{ updatedAt: "desc" }, { id: "asc" }] })); });
  it("maps every stored status centrally", () => { expect(portalStatus.map).toEqual({ NEW: "OPEN", OPEN: "OPEN", IN_PROGRESS: "IN_PROGRESS", ESCALATED: "IN_PROGRESS", WAITING_CUSTOMER: "WAITING_FOR_YOU", RESOLVED: "RESOLVED", CLOSED: "CLOSED" }); });
  it("lists owned tickets with search, portal status, and pagination", async () => { mocks.ticket.findMany.mockResolvedValue([base]); mocks.ticket.count.mockResolvedValue(21); const response = await request(app).get("/api/portal/tickets?page=2&limit=10&search=Help&status=OPEN").set(auth("customer", Role.CUSTOMER)); expect(response.body.meta).toMatchObject({ page: 2, total: 21, totalPages: 3 }); expect(mocks.ticket.findMany).toHaveBeenCalledWith(expect.objectContaining({ skip: 10, take: 10, where: expect.objectContaining({ customerId: "customer-a", status: { in: [TicketStatus.NEW, TicketStatus.OPEN] } }) })); });
  it("returns IDOR-safe not found and a public-only detail shape", async () => { mocks.ticket.findFirst.mockResolvedValueOnce(null); const missing = await request(app).get("/api/portal/tickets/other").set(auth("customer", Role.CUSTOMER)); expect(missing.status).toBe(404); mocks.ticket.findFirst.mockResolvedValueOnce({ ...base, description: "Details", messages: [{ id: "m", body: "Reply", createdAt: new Date(), author: { id: "agent", name: "Mariam", role: Role.ADMIN } }] }); const own = await request(app).get("/api/portal/tickets/ticket-a").set(auth("customer", Role.CUSTOMER)); expect(own.body.data.messages[0].author).toEqual({ id: "agent", name: "Mariam", kind: "SUPPORT" }); expect(JSON.stringify(own.body)).not.toMatch(/priority|assignee|sla|history|notes|email/i); for (const field of ["slaState", "effectiveSlaDueAt", "effectiveSlaTarget", "firstResponseDueAt", "firstRespondedAt", "resolutionDueAt"]) expect(own.body.data).not.toHaveProperty(field); });
  it("returns active safe categories only", async () => { mocks.category.findMany.mockResolvedValue([{ id: "cat", name: "Billing" }]); const response = await request(app).get("/api/portal/categories").set(auth("customer", Role.CUSTOMER)); expect(response.body.data).toEqual([{ id: "cat", name: "Billing" }]); expect(mocks.category.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { isActive: true }, select: { id: true, name: true } })); });
  it("rejects client-owned ticket fields and creates with server defaults plus SLA history", async () => { const rejected = await request(app).post("/api/portal/tickets").set(auth("customer", Role.CUSTOMER)).send({ subject: "Need help", description: "Text", customerId: "other" }); expect(rejected.status).toBe(400); mocks.slaRule.findFirst.mockResolvedValue({ firstResponseMinutes: 30, resolutionMinutes: 120 }); mocks.ticket.create.mockResolvedValue(base); const response = await request(app).post("/api/portal/tickets").set(auth("customer", Role.CUSTOMER)).send({ subject: "Need help", description: "Text" }); expect(response.status).toBe(201); expect(mocks.ticket.create.mock.calls[0][0].data).toMatchObject({ customerId: "customer-a", status: "NEW", priority: "MEDIUM", channel: "WEB", assignedAgentId: null }); expect(mocks.ticket.create.mock.calls[0][0].data.firstResponseDueAt).toBeInstanceOf(Date); expect(mocks.ticketHistory.create).toHaveBeenCalledWith({ data: expect.objectContaining({ actorUserId: "customer", action: "TICKET_CREATED" }) }); });
  it.each([[TicketStatus.WAITING_CUSTOMER, TicketStatus.IN_PROGRESS], [TicketStatus.RESOLVED, TicketStatus.OPEN]])("atomically replies and transitions %s", async (from, to) => { mocks.ticket.findFirst.mockResolvedValue({ id: "ticket-a", status: from }); mocks.ticketMessage.create.mockResolvedValue({ id: "m", body: "Please reopen", createdAt: new Date(), author: { id: "customer", name: "Ahmed", role: Role.CUSTOMER } }); const response = await request(app).post("/api/portal/tickets/ticket-a/messages").set(auth("customer", Role.CUSTOMER)).send({ body: "  Please reopen  " }); expect(response.status).toBe(201); expect(mocks.ticketMessage.create.mock.calls[0][0].data).toMatchObject({ authorUserId: "customer", body: "Please reopen" }); expect(mocks.ticket.update).toHaveBeenCalledWith({ where: { id: "ticket-a" }, data: expect.objectContaining({ status: to }) }); expect(mocks.ticketHistory.create).toHaveBeenCalledWith({ data: expect.objectContaining({ oldValue: from, newValue: to }) }); expect(JSON.stringify(mocks.ticket.update.mock.calls)).not.toContain("firstRespondedAt"); });
  it("rejects closed and non-owned replies safely", async () => { mocks.ticket.findFirst.mockResolvedValueOnce({ id: "ticket-a", status: TicketStatus.CLOSED }); expect((await request(app).post("/api/portal/tickets/ticket-a/messages").set(auth("customer", Role.CUSTOMER)).send({ body: "reply" })).body.error.code).toBe("TICKET_CLOSED"); mocks.ticket.findFirst.mockResolvedValueOnce(null); expect((await request(app).post("/api/portal/tickets/other/messages").set(auth("customer", Role.CUSTOMER)).send({ body: "reply" })).status).toBe(404); });
});
