export const AUDIT_ACTIONS = {
  USER_CREATED: "USER_CREATED", USER_UPDATED: "USER_UPDATED", USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_ACTIVATED: "USER_ACTIVATED", USER_DEACTIVATED: "USER_DEACTIVATED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED", PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED", PROFILE_UPDATED: "PROFILE_UPDATED",
  CUSTOMER_CREATED: "CUSTOMER_CREATED", CUSTOMER_UPDATED: "CUSTOMER_UPDATED", CUSTOMER_DELETED: "CUSTOMER_DELETED", CUSTOMER_NOTE_ADDED: "CUSTOMER_NOTE_ADDED",
  TICKET_CREATED: "TICKET_CREATED", TICKET_STATUS_CHANGED: "TICKET_STATUS_CHANGED", TICKET_PRIORITY_CHANGED: "TICKET_PRIORITY_CHANGED",
  TICKET_CATEGORY_CHANGED: "TICKET_CATEGORY_CHANGED", TICKET_ASSIGNED: "TICKET_ASSIGNED", TICKET_ESCALATED: "TICKET_ESCALATED", TICKET_CLOSED: "TICKET_CLOSED",
  CATEGORY_CREATED: "CATEGORY_CREATED", CATEGORY_UPDATED: "CATEGORY_UPDATED", CATEGORY_DELETED: "CATEGORY_DELETED",
  SLA_RULE_CREATED: "SLA_RULE_CREATED", SLA_RULE_UPDATED: "SLA_RULE_UPDATED", SLA_RULE_DELETED: "SLA_RULE_DELETED",
  DEPARTMENT_CREATED: "DEPARTMENT_CREATED", DEPARTMENT_UPDATED: "DEPARTMENT_UPDATED",
  DEPARTMENT_ACTIVATED: "DEPARTMENT_ACTIVATED", DEPARTMENT_DEACTIVATED: "DEPARTMENT_DEACTIVATED", DEPARTMENT_DELETED: "DEPARTMENT_DELETED",
  BRANCH_CREATED: "BRANCH_CREATED", BRANCH_UPDATED: "BRANCH_UPDATED",
  BRANCH_ACTIVATED: "BRANCH_ACTIVATED", BRANCH_DEACTIVATED: "BRANCH_DEACTIVATED", BRANCH_DELETED: "BRANCH_DELETED",
  TEAM_CREATED: "TEAM_CREATED", TEAM_UPDATED: "TEAM_UPDATED",
  TEAM_ACTIVATED: "TEAM_ACTIVATED", TEAM_DEACTIVATED: "TEAM_DEACTIVATED", TEAM_DELETED: "TEAM_DELETED",
  TEAM_MANAGER_CHANGED: "TEAM_MANAGER_CHANGED",
} as const;

export const AUDIT_ENTITY_TYPES = { USER: "USER", CUSTOMER: "CUSTOMER", TICKET: "TICKET", CATEGORY: "CATEGORY", SLA_RULE: "SLA_RULE", DEPARTMENT: "DEPARTMENT", BRANCH: "BRANCH", TEAM: "TEAM" } as const;
export type AuditChanges = Record<string, { from?: string | number | boolean | null; to?: string | number | boolean | null }>;
