export const AUDIT_ACTIONS = {
  USER_CREATED: "USER_CREATED", USER_UPDATED: "USER_UPDATED", USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  USER_ACTIVATED: "USER_ACTIVATED", USER_DEACTIVATED: "USER_DEACTIVATED",
  CUSTOMER_CREATED: "CUSTOMER_CREATED", CUSTOMER_UPDATED: "CUSTOMER_UPDATED", CUSTOMER_DELETED: "CUSTOMER_DELETED", CUSTOMER_NOTE_ADDED: "CUSTOMER_NOTE_ADDED",
  TICKET_CREATED: "TICKET_CREATED", TICKET_STATUS_CHANGED: "TICKET_STATUS_CHANGED", TICKET_PRIORITY_CHANGED: "TICKET_PRIORITY_CHANGED",
  TICKET_CATEGORY_CHANGED: "TICKET_CATEGORY_CHANGED", TICKET_ASSIGNED: "TICKET_ASSIGNED", TICKET_ESCALATED: "TICKET_ESCALATED", TICKET_CLOSED: "TICKET_CLOSED",
  CATEGORY_CREATED: "CATEGORY_CREATED", CATEGORY_UPDATED: "CATEGORY_UPDATED", CATEGORY_DELETED: "CATEGORY_DELETED",
  SLA_RULE_CREATED: "SLA_RULE_CREATED", SLA_RULE_UPDATED: "SLA_RULE_UPDATED", SLA_RULE_DELETED: "SLA_RULE_DELETED",
} as const;

export const AUDIT_ENTITY_TYPES = { USER: "USER", CUSTOMER: "CUSTOMER", TICKET: "TICKET", CATEGORY: "CATEGORY", SLA_RULE: "SLA_RULE" } as const;
export type AuditChanges = Record<string, { from?: string | number | boolean | null; to?: string | number | boolean | null }>;
